language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors 
# command to run tests
env:
  - DJANGO_VERSION=1.5
script:
  - coverage run --source=nuntium,contactos manage.py test nuntium contactos
  - coverage report -m
after_script:
  - coveralls --verbose
